apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dispenser.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dispenser.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
